[env]
TERM = "xterm-256color"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 250
lines = 400

[window]
decorations = "None"

opacity = 0.95
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 12

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new","-A","-s","alacritty"]
